name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} '
          cd Project-Hungry-Heroes || git clone https://github.com/shilemon/Project-Hungry-Heroes.git &&
          cd Project-Hungry-Heroes &&
          git pull &&
          docker-compose down &&
          docker-compose up --build -d
        '
